server:
  port: ${CUSTOM.SERVER.PORT:9990}

### Mongo database configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://mitocode:mitocode@localhost:27017/mitocode?authSource=admin}


#Actuator configuration
info:
  app:
    name: Audit Service Mitocode
    description: Módulo de la arquitectura de Microservicios que disponibiliza la información de los productos
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator
  tracing:
    sampling:
      probability: 1.0

# Logging Configuration
logging:
  level:
    org:
      springframework:
        web: ALL

# OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: false
    # http://127.0.0.1:9020/api-docs
  swagger-ui:
    enabled: false 
    path: /openapi.yml
    # http://127.0.0.1:9020/swagger-ui/index.html

# Kafka Configuration
mitocode:
  kafka:
    serverHost: 127.0.0.1
    serverPort: 9092
    topicName: mitocode