server:
  port: ${CUSTOM.SERVER.PORT:9020}

mitocode:
  datasources:
    - config01:
      url:
      username:
      password: 
    - config02:
      url:
      username:
### Mongo database configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://mitocode:mitocode@localhost:27017/mitocode?authSource=admin}

### Postgresql database configuration
  jpa:
    databasePlatform: 
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRESQL.URL.CONNECTION:jdbc:postgresql://localhost:5432/mitocode}
    username: mitocode
    password: mitocode
#hibernate:
  #dialect: org.hibernate.dialect.PostgreSQLDialect

#Actuator configuration
info:
  app:
    name: Product Service Mitocode
    description: Módulo de la arquitectura de Microservicios que disponibiliza la información de los productos
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator
  tracing:
    sampling:
      probability: 1.0

# Logging Configuration
logging:
  level:
    org:
      springframework:
        web: ALL

# OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    # http://127.0.0.1:9020/api-docs
  swagger-ui:
    enabled: true
    # http://127.0.0.1:9020/swagger-ui/index.html